-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id_type" DROP NOT NULL,
ALTER COLUMN "id_number" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL;
